---
# tasks file for ansible-role-nsd

- name: Assertions
  assert:
    that:
        - ansible_os_family in [ 'Debian', 'OpenBSD' ]

- name: APT install NSD
  when: ansible_pkg_mgr == 'apt'
  apt:
      name: nsd
      state: present
      update_cache: yes
      cache_valid_time: 3600

- name: Create conf.d directory
  file:
      path: '{{ nsd_conf_d }}'
      state: directory
      owner: root
      group: 0
      mode: 0o755

- name: Use the conf.d directory
  lineinfile:
      dest: '{{ nsd_conf }}'
      line: 'include: "{{ nsd_conf_d }}/*.conf"'
      insertafter: EOF
      state: present
  notify:
      - Restart NSD

- name: Add server block
  lineinfile:
      dest: '{{ nsd_conf }}'
      line: 'server:'
      insertbefore: BOF
      state: present

- name: Configure
  with_dict: '{{ nsd_config }}'
  lineinfile:
      dest: '{{ nsd_conf }}'
      line: '{{ item.key }}: {{ item.value }}'
      regexp: '{{ item.key }}:'
      insertafter: 'server:'
  notify:
      - Restart NSD

- name: Copy configuration templates
  with_fileglob:
      - templates/nsd/conf.d/*
      - '{{ playbook_dir }}/templates/nsd/conf.d/*'
  template:
      src: '{{ item }}'
      dest: '{{ nsd_conf_d }}/'
      owner: root
      group: 0
      mode: 0o644
  notify:
      - Restart NSD

- name: Copy zones
  with_fileglob:
      - templates/nsd/zones/*
      - '{{ playbook_dir }}/templates/nsd/zones/*'
  template:
      src: '{{ item }}'
      dest: '{{ nsd_zones }}/'
      owner: root
      group: 0
      mode: 0o644
  notify:
      - Restart NSD

- name: Alias emails to root
  when: nsd_mail_alias is defined
  lineinfile:
      dest: '{{ aliases_file[ansible_os_family] }}'
      create: yes
      line: '{{ nsd_user[ansible_os_family] }}: {{ nsd_mail_alias }}'
      regexp: '{{ nsd_user[ansible_os_family] }}:'
  notify:
      - Update SMTPd database

- name: Enable NSD
  service:
      name: nsd
      enabled: yes
      state: started

- meta: flush_handlers

- name: Wait for NSD to recieve requests
  wait_for:
      port: 53
