---
# handlers file for ansible-role-nsd

- name: Restart NSD
  service:
      name: nsd
      state: restarted

- name: Update SMTPd database
  when: ansible_os_family == 'OpenBSD'
  command: /usr/bin/newaliases
